name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./quirknotes/backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install MongoDB community repo
      run: |
        sudo apt-get install -y mongodb-org

    - name: Start MongoDB
      run: |
        sudo systemctl start mongod

    - name: Verify MongoDB is running
      run: |
        sudo systemctl status mongod

    - name: Run server.js
      run: |
        node server.js &

    - run: npm i
    - run: npm test
